### ISSUE TITLE
First line of code fence is incorrectly parsed as header for purposes of coherence

### ISSUE THREAD

**Issue by dharmab** [frnmst/md-toc#11]
In 5.0.0, the first line of a code fence is being parsed for purposes of header coherence. This results in a `TocDoesNotRenderAsCoherentList` error when using the api, and a truncated TOC when using the CLI.

API:
~~~
[INFO] Generating table of contents for /mnt/infrastructure/docs/ingressroute.md
Traceback (most recent call last):
  File "src/generate.py", line 325, in <module>
    main()
  File "src/generate.py", line 321, in main
    _generate_table_of_contents()
  File "src/generate.py", line 230, in _generate_table_of_contents
    index[filename] = md_toc.build_toc(filename, keep_header_levels=6, parser='github')
  File "/usr/local/lib/python3.7/site-packages/md_toc/api.py", line 213, in build_toc
    raise TocDoesNotRenderAsCoherentList
md_toc.exceptions.TocDoesNotRenderAsCoherentList
~~~

CLI, with minimal test case:
~~~
[dharmab@n7 md-toc]$ cat test1.md 
# Foo1

## Foo2

### Foo3

```
#!/bin/bash
code
```

### Foo4
[dharmab@n7 md-toc]$ md_toc test1.md github
- [Foo1](#foo1)
  - [Foo2](#foo2)
    - [Foo3](#foo3)
[dharmab@n7 md-toc]$ cat test2.md 
# Foo1

## Foo2

### Foo3

```
code
#!/bin/bash
code
```

### Foo4
[dharmab@n7 md-toc]$ md_toc test2.md github
- [Foo1](#foo1)
  - [Foo2](#foo2)
    - [Foo3](#foo3)
    - [Foo4](#foo4)
~~~

**Comment by dharmab** [comment]
It looks like the code fence state is being initialized here: https://github.com/frnmst/md-toc/blob/5.0.0/md_toc/api.py#L152

Which means that in this block, the first line is always skipped: https://github.com/frnmst/md-toc/blob/5.0.0/md_toc/api.py#L176-L185


Oh how I wish Python had do-while loops...

**Comment by frnmst** [comment]
Thanks.
I can reproduce the CLI bug, but the exception is not raised by the API (using your `test1.md` example):

```shell
$ python -m md_toc test1.md github
- [Foo1](#foo1)
  - [Foo2](#foo2)
    - [Foo3](#foo3)
```
```python
>>> import md_toc
>>> print(md_toc.build_toc('test1.md', keep_header_levels=6, parser='github'))
- [Foo1](#foo1)
  - [Foo2](#foo2)
    - [Foo3](#foo3)

```
Anyway I see what the problem was thanks to #12
