### ISSUE TITLE
API: `write_string_on_file_between_markers` destructively fails if marker is at end of file

### ISSUE THREAD

**Issue by dharmab** [frnmst/md-toc#8]
If the `marker` passed to `write_string_on_file_between_markers` is at the end of the file, A LineOutOfFileBoundsError is raised and the marker is erased from the file.

```
[INFO] Generating README table of contents
Traceback (most recent call last):
  File "src/generate.py", line 321, in <module>
    main()
  File "src/generate.py", line 317, in main
    _generate_table_of_contents()
  File "src/generate.py", line 261, in _generate_table_of_contents
    md_toc.write_string_on_file_between_markers('/mnt/infrastructure/README.md', readme_toc, marker='[](TOC)')
  File "/usr/local/lib/python3.7/site-packages/md_toc/api.py", line 70, in write_string_on_file_between_markers
    append=False)
  File "/usr/local/lib/python3.7/site-packages/fpyutils/filelines.py", line 148, in insert_string_at_line
    raise LineOutOfFileBoundsError
```

**Comment by frnmst** [comment]
Thank you for reporting this. It seems to happen if `marker` is present in the last line of a file.
As a temporary workaround you might want to append a new line to the files until it gets fixed.
Anyway, it's a problem with [fpyutils](https://github.com/frnmst/fpyutils)

**Comment by frnmst** [comment]
Should be fixed. Feel free to re-open if it's not
